# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
          - COMPILERCXX=g++-4.9
          - COMPILERC=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
          - COMPILERCXX=g++-5
          - COMPILERC=gcc-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
          - COMPILERCXX=g++-6
          - COMPILERC=gcc-6

before_install:
    - travis_retry sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - travis_retry sudo apt-get -qq update -y
    - sudo apt-get install cmake libvirt-dev uuid-dev

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$COMPILERCXX -DCMAKE_C_COMPILER=$COMPILERC ..
    - make

notifications:
  recipients:
    - spickartz@eonerc.rwth-aachen.de
    - tohliger@eonerc.rwth-aachen.de
  email:
    on_success: change
    on_failure: always
